services:
  peteco-app:
    container_name: peteco-app
    user: node
    restart: unless-stopped
    tty: true
    build:
      dockerfile: ./.config/docker/node/Dockerfile.deploy
    volumes:
      - ./:/app/
    networks:
      - peteco-network
  peteco-server:
    container_name: peteco-server
    restart: unless-stopped
    tty: true
    build:
      dockerfile: ./.config/docker/nginx/Dockerfile.deploy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.config/docker/nginx/conf/route.conf:/etc/nginx/conf.d/route.conf
      - ./.config/docker/nginx/letsencrypt/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - peteco-network
    depends_on:
      - peteco-app
networks:
  peteco-network:
    name: peteco-network
    driver: bridge