services:
  peteco-app:
    container_name: peteco-app
    user: node
    restart: unless-stopped
    tty: true
    build:
      dockerfile: ./.config/docker/node/Dockerfile.local
    volumes:
      - ./:/app/
    ports:
      - ${APP_HTTP_PORT-4040}:3000
    networks:
      - peteco-network
    environment:
      - NODE_ENV=${NODE_ENV}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}

networks:
  peteco-network:
    name: peteco-network
    driver: bridge
