# Usar uma versão otimizada do Node.js para produção
FROM node:alpine

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Instalar dependências de produção
RUN npm install --production

# Expor a porta 3000 para acesso à aplicação
EXPOSE 3000

# Rodar a aplicação com o comando npm run start
CMD ["npm", "run", "start"]
